### ISSUE TITLE
Path to service properties is wrong

### ISSUE THREAD

**Issue by thopewell** [kodefoundry/xconf-docker#1]
Hi Biju,

I haven't untangled where this path is set, but inside the container I can see you are starting the process:

```
/var/lib/jetty/webapps/service/WEB-INF $ ps
PID   USER     TIME  COMMAND
    1 jetty     0:18 /usr/lib/jvm/java-1.8-openjdk/jre/bin/java -DappConfig=/var/lib/jetty/webapps/WEB-INF/classes/service.properties -DserviceName=xconfDataService -Xms2048m -Xmx2048m -XX:NewSize=512m -XX:MaxNewSize=512m -X
   60 jetty     0:00 /bin/sh
   76 jetty     0:00 ps
```
note:
```
-DappConfig=/var/lib/jetty/webapps/WEB-INF/classes/service.properties
```
but the configuration path has "services" in it, so I don't think your service.properties file is being picked up:

```
/var/lib/jetty/webapps/service/WEB-INF/classes $ pwd
/var/lib/jetty/webapps/service/WEB-INF/classes
/var/lib/jetty/webapps/service/WEB-INF/classes $ ls service.properties 
service.properties
```

**Comment by thopewell** [comment]
To clarify, out of the box:

```
/var/lib/jetty/webapps/service/WEB-INF $ pwd
/var/lib/jetty/webapps/service/WEB-INF
/var/lib/jetty/webapps/service/WEB-INF $ cat service.properties 

autoGenerateSchema=true
 connectionPools.SharedConnectionPool.maxConnsPerHost=15
 connectionPools.SharedConnectionPool.seeds=cassandra
```

I think we need to modify:
https://github.com/kodefoundry/xconf-docker/blob/master/adminservice/Dockerfile#L106
https://github.com/kodefoundry/xconf-docker/blob/master/adminservice/Dockerfile#L120

Will try/test and open a PR later...

**Comment by thopewell** [comment]
https://github.com/kodefoundry/xconf-docker/pull/2/files

**Comment by thopewell** [comment]
Not quite working yet, there is a new error:
```
 InvalidRequestException(why:Cannot add already existing table "LogFileList" to keyspace "ApplicationsDiscoveryDataService")
```
but at least the DB connection is there!

**Comment by kodefoundry** [comment]
I merged you PR and I see that DB connection is working fine.
Regarding the issue you reported
InvalidRequestException(why:Cannot add already existing table "LogFileList" to keyspace "ApplicationsDiscoveryDataService")
This is because I guess table "LogFileList" is already being created by "adminservice". I tested this by commenting of "adminservice" and running docker-compose, then data service is running without any issues. We have to see how to avoid this, think through it, maybe you might have some idea.

I also ran the "adminservice" and looks like the admin service is coming up alright, but there is still some problem in the way the component is built, I felt there is some issue with the CSS. The UI is not rendering as it should have

Thanks for you input's, at least together we made some progress.

**Comment by kodefoundry** [comment]
Another update, now I am not seeing the "LogFileList" error now. The sequence what I did is as below
1. I downloaded build and ran docker-compose up after merging your PR
    [Result] - Services came up, but I saw "LogFileList" error as you reported
2. I commented "adminservice" part in the docker-compose file and ran docker-compose up to run "cassandra" and "dataservice" only
    [Result] - "dataservice" came up smoothly without any error
3. I uncommented "adminservice" part and ran docker-compose up again
    [Result] - Now I see both the services came up together without any errors.

**Comment by kodefoundry** [comment]
I tried to investigate the issue in adminservice, looks like the npm install part

npm install -g bower
npm install -g grunt-cli
npm install
npm install grunt-contrib-copy --save-den 
grunt install

did't happen properly. I saw no angular defined in the browser console, so I went and checked inside node_modules there was not angular/bootstrap etc..
could't make out exactly why though!!

**Comment by kodefoundry** [comment]
My latest checkin should fix this error you are getting
InvalidRequestException(why:Cannot add already existing table "LogFileList" to keyspace "ApplicationsDiscoveryDataService")
Please check and confirm.
I have made adminservice depend on healthy startup of dataservice using a health check.
This avoids both of the services trying to create table LogFileList together when services are coming up for the very first time and cassandra db is empty
